CREATE DATABASE IF NOT EXISTS cadastro_clientes;
USE cadastro_clientes;

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  cidade VARCHAR(120) NOT NULL,
  nivel VARCHAR(50) NOT NULL,
  atualizacao DATETIME NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
